// <auto-generated />
using System;
using DnD_Character_Sheet_Creator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnD_Character_Sheet_Creator.Migrations
{
    [DbContext(typeof(DnDDbContext))]
    [Migration("20260710020958_AlignModelForSeedAndSchema")]
    partial class AlignModelForSeedAndSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharacterEquipment", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("CharacterEquipment");
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("AttachmentId");

                    b.HasIndex("CharacterId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<bool>("AcrobaticsProficient")
                        .HasColumnType("bit");

                    b.Property<int>("Alignment")
                        .HasColumnType("int");

                    b.Property<bool>("AnimalHandlingProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("ArcanaProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("AthleticsProficient")
                        .HasColumnType("bit");

                    b.Property<int>("Background")
                        .HasColumnType("int");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<bool>("CharismaSaveProficient")
                        .HasColumnType("bit");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<bool>("ConstitutionSaveProficient")
                        .HasColumnType("bit");

                    b.Property<int>("CurrentExperiencePoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfLastLevelUp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeceptionProficient")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<bool>("DexteritySaveProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("HistoryProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("InsightProficient")
                        .HasColumnType("bit");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<bool>("IntelligenceSaveProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("IntimidationProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("InvestigationProficient")
                        .HasColumnType("bit");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<bool>("MedicineProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("NatureProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("PerceptionProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("PerformanceProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("PersuasionProficient")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Race")
                        .HasColumnType("int");

                    b.Property<bool>("ReligionProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("SleightOfHandProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("StealthProficient")
                        .HasColumnType("bit");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<bool>("StrengthSaveProficient")
                        .HasColumnType("bit");

                    b.Property<bool>("SurvivalProficient")
                        .HasColumnType("bit");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.Property<bool>("WisdomSaveProficient")
                        .HasColumnType("bit");

                    b.HasKey("CharacterId");

                    b.HasIndex("LevelId")
                        .IsUnique()
                        .HasFilter("[LevelId] IS NOT NULL");

                    b.HasIndex("PlayerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.CharacterLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<int>("CurrentExperiencePoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfLastLevelUp")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExperiencePointsToNextLevel")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("int");

                    b.HasKey("LevelId");

                    b.ToTable("CharacterLevels");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            CurrentExperiencePoints = 0,
                            DateOfLastLevelUp = new DateTime(2026, 7, 10, 2, 9, 57, 528, DateTimeKind.Utc).AddTicks(7680),
                            ExperiencePointsToNextLevel = 300,
                            Level = 1,
                            ProficiencyBonus = 2
                        },
                        new
                        {
                            LevelId = 2,
                            CurrentExperiencePoints = 300,
                            DateOfLastLevelUp = new DateTime(2026, 7, 10, 2, 9, 57, 528, DateTimeKind.Utc).AddTicks(7875),
                            ExperiencePointsToNextLevel = 900,
                            Level = 2,
                            ProficiencyBonus = 2
                        },
                        new
                        {
                            LevelId = 3,
                            CurrentExperiencePoints = 900,
                            DateOfLastLevelUp = new DateTime(2026, 7, 10, 2, 9, 57, 528, DateTimeKind.Utc).AddTicks(7878),
                            ExperiencePointsToNextLevel = 2700,
                            Level = 3,
                            ProficiencyBonus = 2
                        },
                        new
                        {
                            LevelId = 4,
                            CurrentExperiencePoints = 2700,
                            DateOfLastLevelUp = new DateTime(2026, 7, 10, 2, 9, 57, 528, DateTimeKind.Utc).AddTicks(7879),
                            ExperiencePointsToNextLevel = 6500,
                            Level = 4,
                            ProficiencyBonus = 2
                        },
                        new
                        {
                            LevelId = 5,
                            CurrentExperiencePoints = 6500,
                            DateOfLastLevelUp = new DateTime(2026, 7, 10, 2, 9, 57, 528, DateTimeKind.Utc).AddTicks(7880),
                            ExperiencePointsToNextLevel = 14000,
                            Level = 5,
                            ProficiencyBonus = 3
                        });
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment");

                    b.HasDiscriminator().HasValue("Equipment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.AdventuringGear", b =>
                {
                    b.HasBaseType("DnD_Character_Sheet_Creator.Models.Equipment");

                    b.HasDiscriminator().HasValue("AdventuringGear");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1003,
                            Cost = 2,
                            Name = "Backpack",
                            Type = "Gear",
                            Weight = 5
                        },
                        new
                        {
                            EquipmentId = 1015,
                            Cost = 25,
                            Name = "Thieves' Tools",
                            Type = "Gear",
                            Weight = 1
                        });
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.Armour", b =>
                {
                    b.HasBaseType("DnD_Character_Sheet_Creator.Models.Equipment");

                    b.Property<int>("ArmourClass")
                        .HasColumnType("int");

                    b.Property<bool>("StealthDisadvantage")
                        .HasColumnType("bit");

                    b.Property<int>("StrenghtRequierment")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Armour");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1002,
                            Cost = 75,
                            Name = "Chain Mail",
                            Type = "Armour",
                            Weight = 55,
                            ArmourClass = 0,
                            StealthDisadvantage = false,
                            StrenghtRequierment = 0
                        });
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.Weapon", b =>
                {
                    b.HasBaseType("DnD_Character_Sheet_Creator.Models.Equipment");

                    b.Property<string>("DamageAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("WeaponProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Weapon");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1001,
                            Cost = 15,
                            Name = "Longsword",
                            Type = "Weapon",
                            Weight = 3,
                            DamageAmount = "1d8",
                            DamageType = "Slashing",
                            WeaponProperties = "[]"
                        },
                        new
                        {
                            EquipmentId = 1004,
                            Cost = 25,
                            Name = "Rapier",
                            Type = "Weapon",
                            Weight = 2,
                            DamageAmount = "1d8",
                            DamageType = "Piercing",
                            WeaponProperties = "[]"
                        },
                        new
                        {
                            EquipmentId = 1025,
                            Cost = 2,
                            Name = "Dagger",
                            Type = "Weapon",
                            Weight = 1,
                            DamageAmount = "1d4",
                            DamageType = "Piercing",
                            WeaponProperties = "[]"
                        });
                });

            modelBuilder.Entity("CharacterEquipment", b =>
                {
                    b.HasOne("DnD_Character_Sheet_Creator.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD_Character_Sheet_Creator.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.Attachment", b =>
                {
                    b.HasOne("DnD_Character_Sheet_Creator.Models.Character", "Character")
                        .WithMany("Attachments")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.Character", b =>
                {
                    b.HasOne("DnD_Character_Sheet_Creator.Models.CharacterLevel", "Level")
                        .WithOne()
                        .HasForeignKey("DnD_Character_Sheet_Creator.Models.Character", "LevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnD_Character_Sheet_Creator.Models.Player", "Player")
                        .WithMany("CharacterList")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DnD_Character_Sheet_Creator.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DnD_Character_Sheet_Creator.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD_Character_Sheet_Creator.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DnD_Character_Sheet_Creator.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.Character", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("DnD_Character_Sheet_Creator.Models.Player", b =>
                {
                    b.Navigation("CharacterList");
                });
#pragma warning restore 612, 618
        }
    }
}
