global using System;
global using System.Net;
global using System.Net.Http;
global using System.Net.Http.Json;
global using System.Threading.Tasks;
global using System.Collections.Generic;
global using System.Linq;
global using Xunit;
global using Microsoft.Extensions.DependencyInjection;
